project_id = "pvvbglukaehizykkpaes"

[functions.fish-advice-chat]
enabled = true
verify_jwt = false

[functions.send-order-email]
enabled = true
verify_jwt = false

[functions.verify-payment]
enabled = true
verify_jwt = false

[functions.google-drive-auth]
enabled = true
verify_jwt = false

[functions.system-backup]
enabled = true
verify_jwt = false

[functions.chatbot]
enabled = true
verify_jwt = false

[functions.steadfast-courier]
enabled = true
verify_jwt = false

[functions.steadfast-webhook]
enabled = true
verify_jwt = false

[functions.send-whatsapp]
enabled = true
verify_jwt = false

[functions.track-order]
enabled = true
verify_jwt = false