-- =========================================================================
-- Catalog module schema (Phase 2 — Categories, Brands, Product Variations)
-- Mirrors Supabase catalog tables. Only product_variations is created here.
-- categories & brands are already defined in complete_schema.sql and are
-- reused by the /api/categories and /api/brands routes.
--
-- product_variations uses CHAR(36) UUIDs generated by the API layer so that
-- the same client-side facade can carry ids for both Supabase and MySQL.
-- product_id is VARCHAR(64) to accept both int (existing MySQL products)
-- and uuid (Supabase migrations copied into MySQL) references, so no FK.
-- Safe to re-run: everything uses IF NOT EXISTS.
-- =========================================================================

CREATE TABLE IF NOT EXISTS product_variations (
  id CHAR(36) NOT NULL PRIMARY KEY,
  product_id VARCHAR(64) NOT NULL,
  variation_name VARCHAR(255) NOT NULL,
  unit VARCHAR(32) NOT NULL DEFAULT 'kg',
  weight_value DECIMAL(12,3) NOT NULL DEFAULT 0,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  cost_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  stock_quantity INT NOT NULL DEFAULT 0,
  sku VARCHAR(128) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_pv_product (product_id),
  INDEX idx_pv_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
