// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list_products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { z } from "npm:zod@^3.25.76";
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List products from the FishCare shop catalog with optional search.",
  inputSchema: {
    search: z.string().optional().describe("Optional keyword to filter by name."),
    limit: z.number().int().min(1).max(50).default(20).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("products").select("id,name,price,cost_price,stock_quantity,category_id,image_url").limit(limit);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_market_prices.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_market_prices_default = defineTool2({
  name: "list_market_prices",
  title: "List market prices",
  description: "List recent fish market prices submitted by users across Bangladesh.",
  inputSchema: {
    fish_name: z2.string().optional().describe("Optional fish name filter."),
    location: z2.string().optional().describe("Optional location filter (district/market)."),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ fish_name, location, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("market_prices").select("*").order("created_at", { ascending: false }).limit(limit);
    if (fish_name) q = q.ilike("fish_name", `%${fish_name}%`);
    if (location) q = q.ilike("location", `%${location}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { prices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_fish_species.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { FISH_SPECIES_OPTIONS } from "npm:@/data/fishSpeciesOptions";
import { z as z3 } from "npm:zod@^3.25.76";
var list_fish_species_default = defineTool3({
  name: "list_fish_species",
  title: "List fish species",
  description: "List the fish species supported by FishCare calculators and content.",
  inputSchema: {
    search: z3.string().optional().describe("Optional keyword filter (matches Bangla or English name).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search }) => {
    const list = search ? FISH_SPECIES_OPTIONS.filter((s) => {
      const q = search.toLowerCase();
      return JSON.stringify(s).toLowerCase().includes(q);
    }) : FISH_SPECIES_OPTIONS;
    return {
      content: [{ type: "text", text: JSON.stringify(list) }],
      structuredContent: { species: list }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "fishcare-mcp",
  title: "FishCare MCP",
  version: "0.1.0",
  instructions: "Tools for the FishCare app: browse the shop product catalog, look up recent fish market prices across Bangladesh, and list supported fish species.",
  tools: [list_products_default, list_market_prices_default, list_fish_species_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
